apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: simple-api
  description: Simple test API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition: |
    openapi: 3.0.0
    info:
      title: Simple API
      version: 1.0.0
    paths:
      /test:
        get:
          responses:
            '200':
              description: OK

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
	name: nginx
	description: Example NGINX service
	annotations:
		backstage.io/kubernetes-id: nginx
		kubernetes.io/managed-by: backstage
spec:
	type: service
	owner: user:guest
	lifecycle: production

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: Backchat Plugin
#   description: An example of a Backstage application.
#   # Example for optional annotations
#   annotations:
#     sonarqube.org/project-key: bhaskar
#   #   github.com/project-slug: backstage/backstage
#   #   backstage.io/techdocs-ref: dir:.

# spec:
#   type: service
#   owner: Ben Wilcock
#   lifecycle: production

